### ISSUE TITLE
[feature] add ability to manage test runs using conftest.py and config.json files 

### ISSUE THREAD

**Issue by odemeniuk** [mxschmitt/pytest-playwright#29]
For my selenium project  I do use solution to manage shared fixtures to control browser versions and options.

In conftest.py file 

```
@pytest.fixture
def config(scope='session'):
    # Read the file
    with open('config.json') as config_file:
        config = json.load(config_file)

    assert config['browser'] in ['Firefox', 'Chrome', 'Headless Chrome']
    assert isinstance(config['implicit_wait'], int)
    assert config['implicit_wait'] > 0
    return config


@pytest.fixture
def browser(config):
    if config['browser'] == 'Firefox':
        b = selenium.webdriver.Firefox()
    elif config['browser'] == 'Chrome':
        b = selenium.webdriver.Chrome()
    elif config['browser'] == 'Headless Chrome':
        opts = selenium.webdriver.ChromeOptions()
        opts.add_argument('headless')
        b = selenium.webdriver.Chrome(options=opts)
    else:
        raise Exception(f'Browser "{config["browser"]}" is not supported')

    b.implicitly_wait(config['implicit_wait'])
    yield b
    b.quit()

```

And config.json will look like 

```
{
  "browser": "Headless Chrome",
  "implicit_wait": 10
}

```

I do see fixtures in pytest_playwright.py - so I assume that those configurable through CLI could be moved into conftest.py file

**Comment by mxschmitt** [comment]
Hi,
what exactly do you want to control with an external file?
In theory you could add custom launch or context arguments by redefining the fixtures.

**Comment by odemeniuk** [comment]
I would like to control browser launch  from conftest.py file  - pytest is auto-discovering it in test directories.

**Comment by mxschmitt** [comment]
Something like that should work then:
```py
        @pytest.fixture(scope="session")
        def launch_arguments(request):
            return {"slowMo": 100}
```
Once you specify that it will overwrite the defaults.

For headless we already have a CLI argument as well for browsers.

**Comment by odemeniuk** [comment]
Got it. I was able to reuse  is_chromium in conftest.py and this is exactly what I was looking for 

```
@pytest.fixture(scope="session")
def is_chromium(browser_name: str) -> bool:
    return browser_name == "chromium"
```


Thank you for pointing me into the right direction.
